package io.github.moxisuki.blockprint.core.tools

import io.github.moxisuki.blockprint.core.BlockState
import io.github.moxisuki.blockprint.core.api.BlockPrintReader
import java.io.File
import java.util.TreeSet

/**
 * JVM-only helper used by the model-baker workflow.
 *
 * It reads any blueprint supported by [BlockPrintReader] and writes the exact,
 * unique blockstate selectors that appear in occupied region data. The output
 * can be passed directly to:
 *
 *   -Dblockprint.baker.blockstateFile=<output>
 */
fun main(args: Array<String>) {
    val options = parseArgs(args)
    val input = options["input"]?.let(::File)
        ?: error("Missing --input <blueprint-file>")
    val output = options["output"]?.let(::File)
        ?: error("Missing --output <blockstate-file>")
    val includeAir = options.containsKey("include-air")
    val allPalette = options.containsKey("all-palette")

    val document = BlockPrintReader.read(input)
    val selectors = TreeSet<String>()

    for (region in document.regions) {
        if (allPalette) {
            for (state in region.palette.entries) {
                addSelector(selectors, state, includeAir)
            }
        } else {
            val usedPaletteIds = region.rawBlocks.toHashSet()
            for (paletteId in usedPaletteIds) {
                val state = region.palette.entries.getOrNull(paletteId) ?: continue
                addSelector(selectors, state, includeAir)
            }
        }
    }

    output.parentFile?.mkdirs()
    output.writeText(
        buildString {
            appendLine("# Generated by WriteBakerBlockstateFile")
            appendLine("# source=${input.absolutePath}")
            appendLine("# states=${selectors.size}")
            for (selector in selectors) {
                appendLine(selector)
            }
        },
        Charsets.UTF_8,
    )

    println("Wrote ${selectors.size} blockstate selectors to ${output.absolutePath}")
}

private fun addSelector(out: MutableSet<String>, state: BlockState, includeAir: Boolean) {
    if (!includeAir && state.name == "minecraft:air") return
    out.add(canonicalSelector(state))
}

private fun canonicalSelector(state: BlockState): String {
    val properties = state.properties
    if (properties.isNullOrEmpty()) return state.name
    return state.name + properties.entries
        .sortedBy { it.key }
        .joinToString(prefix = "[", postfix = "]", separator = ",") { (key, value) ->
            "$key=$value"
        }
}

private fun parseArgs(args: Array<String>): Map<String, String> {
    val out = linkedMapOf<String, String>()
    var i = 0
    while (i < args.size) {
        when (val arg = args[i]) {
            "--input", "-i" -> {
                i++
                out["input"] = args.getOrNull(i) ?: error("$arg requires a value")
            }
            "--output", "-o" -> {
                i++
                out["output"] = args.getOrNull(i) ?: error("$arg requires a value")
            }
            "--include-air" -> out["include-air"] = "true"
            "--all-palette" -> out["all-palette"] = "true"
            "--help", "-h" -> {
                printUsage()
                kotlin.system.exitProcess(0)
            }
            else -> error("Unknown argument: $arg")
        }
        i++
    }
    return out
}

private fun printUsage() {
    println(
        """
        Usage:
          WriteBakerBlockstateFile --input <blueprint> --output <palette.blockstates.txt>

        Options:
          --include-air   Include minecraft:air.
          --all-palette   Emit every palette entry, including entries not used by block data.
        """.trimIndent(),
    )
}
